
http:
  port: 8090
# domain: localhost
# protocol: http

# loginfo 
log:
  level: debug #  debug info warn error

#db
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 
  db_name: wallet
  charset: utf8mb4



